#!/usr/bin/env python3
"""Generate `icons.py` — the collection ICON SET — from lucide-static.

The pack is Lucide, the same 24x24 stroke style the nav bar already draws by
hand, so a collection's icon sits next to them without looking imported. Only a
CURATED subset is vendored: the model has to pick a name that exists, so the
valid names travel over MCP (save_collection's docstring lists them) and a list
of 2,000 wouldn't fit. Everything here is a topic a collection plausibly is.

    npm pack lucide-static && tar xzf lucide-static-*.tgz
    python3 scripts/build_icon_set.py package/icons

Re-run only to add names to CURATED (or to move to a newer Lucide); the output
is checked in so the app needs no npm at runtime.
"""
import re
import sys
from pathlib import Path

# Grouped only for the docstring the model reads — the file itself is flat.
CURATED = {
    "food & drink": ["utensils", "chef-hat", "cooking-pot", "pizza", "sandwich",
                     "salad", "soup", "ham", "fish", "egg", "croissant", "cake",
                     "ice-cream-cone", "apple", "carrot", "wheat", "coffee",
                     "wine", "beer", "martini", "cup-soda", "milk"],
    "places & travel": ["plane", "map", "map-pin", "compass", "globe", "mountain",
                        "tent", "palmtree", "waves", "ship", "train-front", "car",
                        "bike", "footprints", "building", "hotel", "landmark",
                        "house"],
    "things & shopping": ["shopping-cart", "shopping-bag", "gift", "package",
                          "shirt", "glasses", "watch", "sofa", "lamp", "wrench",
                          "hammer", "paintbrush", "scissors", "key", "car-front"],
    "media & making": ["book", "book-open", "library", "newspaper", "film",
                       "clapperboard", "tv", "music", "guitar", "mic", "headphones",
                       "camera", "image", "palette", "pen-tool", "feather", "code",
                       "terminal", "gamepad-2", "puzzle"],
    "body & outdoors": ["dumbbell", "heart", "brain", "stethoscope", "pill", "bed",
                        "bath", "leaf", "sprout", "flower", "trees", "sun", "moon",
                        "cloud", "snowflake", "flame", "droplet"],
    "people & work": ["users", "user", "baby", "dog", "cat", "briefcase",
                      "graduation-cap", "presentation", "handshake", "phone",
                      "mail", "message-circle", "calendar", "clock"],
    "money": ["dollar-sign", "credit-card", "piggy-bank", "receipt", "trending-up",
              "chart-pie"],
    "generic": ["folder", "file-text", "notebook-pen", "list-todo", "clipboard-list",
                "bookmark", "tag", "star", "sparkles", "lightbulb", "target",
                "trophy", "flag", "hash", "quote", "link", "archive", "box",
                "layers", "grid-2x2", "circle-check", "zap"],
}
DEFAULT = "folder"   # what an icon-less collection draws


def body(svg: str) -> str:
    """The shapes inside a Lucide <svg>, whitespace-collapsed. The wrapper is
    dropped — the template supplies its own sizing/stroke attributes, exactly
    like the hand-written nav icons."""
    inner = svg[svg.index(">", svg.index("<svg")) + 1: svg.rindex("</svg>")]
    inner = re.sub(r"\s+", " ", inner).strip()
    return re.sub(r"\s*/>", "/>", inner)


def main(src: str) -> int:
    icons = Path(src)
    names = [n for group in CURATED.values() for n in group]
    if len(names) != len(set(names)):
        dupes = sorted({n for n in names if names.count(n) > 1})
        print(f"duplicate names in CURATED: {dupes}", file=sys.stderr)
        return 1
    missing = [n for n in names if not (icons / f"{n}.svg").exists()]
    if missing:
        print(f"not in this Lucide build: {missing}", file=sys.stderr)
        return 1
    out = ['"""Collection icons — a curated Lucide subset. GENERATED by',
           'scripts/build_icon_set.py; edit CURATED there, not this file.',
           "",
           "server.py validates against ICON_NAMES and ships them to the model in",
           "save_collection's docstring; the webapp renders ICON_PATHS[name] inside",
           'its own <svg> wrapper."""',
           "",
           f"DEFAULT_ICON = {DEFAULT!r}",
           "",
           "# Grouped by theme for the model-facing list; the order is the order the",
           "# icon picker shows them in.",
           "ICON_GROUPS = {"]
    for group, members in CURATED.items():
        out.append(f"    {group!r}: {members!r},")
    out += ["}", "",
            "ICON_NAMES = tuple(n for g in ICON_GROUPS.values() for n in g)", "",
            "ICON_PATHS = {"]
    for n in names:
        out.append(f"    {n!r}: {body((icons / f'{n}.svg').read_text())!r},")
    out += ["}", ""]
    Path("icons.py").write_text("\n".join(out))
    print(f"icons.py: {len(names)} icons")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "package/icons"))
